endroid_qr_code:
  writer: 'svg'
  size: 150
  margin: 0
  foreground_color: { r: 0, g: 0, b: 0 }
  background_color: { r: 255, g: 255, b: 255 }
  error_correction_level: low # low, medium, quartile or high
  encoding: UTF-8
  label: Scan the code
  label_font_size: 20
  label_alignment: left # left, center or right
  label_margin: { b: 20 }
  #logo_path: '%kernel.root_dir%/../vendor/endroid/qr-code/assets/images/symfony.png'
  #logo_width: 150
  #logo_height: 200
  validate_result: false # checks if the result is readable
  writer_options:
    exclude_xml_declaration: true