security:
    role_hierarchy:
        ROLE_REGISTED:     ROLE_USER
        ROLE_CENSOR:       ROLE_REGISTED
        ROLE_EDILE:        ROLE_REGISTED
        ROLE_TRIBUNUS:     ROLE_REGISTED
        ROLE_PRETOR:       ROLE_REGISTED
        ROLE_STORY_TELLER: [ROLE_CENSOR, ROLE_EDILE, ROLE_TRIBUNUS, ROLE_PRETOR]
        ROLE_ADMIN: ROLE_REGISTED
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        is_provider:
            entity:
                class: App\Entity\User
                property: username

    #Econder for user password
    encoders:
        App\Entity\User: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            logout:
                path:   /logout
                target: user_security
            form_login:
                login_path: user_login
                check_path: user_login

    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
         - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
         - { path: ^/security, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
         - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
         - { path: ^/, roles: ROLE_USER }
