security:
    role_hierarchy:
        ROLE_REGISTERED:   ROLE_USER
        ROLE_CENSOR:       ROLE_REGISTERED
        ROLE_EDILE:        ROLE_REGISTERED
        ROLE_TRIBUNUS:     ROLE_REGISTERED
        ROLE_PRETOR:       ROLE_REGISTERED
        ROLE_SENATOR:      [ROLE_REGISTERED, ROLE_EDILE, ROLE_CENSOR, ROLE_PRETOR]
        ROLE_EMPEROR:      [ROLE_SENATOR]
        ROLE_STORY_TELLER: [ROLE_CENSOR, ROLE_EDILE, ROLE_TRIBUNUS, ROLE_PRETOR, ROLE_SENATOR, ROLE_EMPEROR]
        ROLE_ADMIN: ROLE_REGISTERED
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        is_provider:
            entity:
                class: App\Entity\User
                property: username

    #Econder for user password
    encoders:
        App\Entity\User: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            switch_user: { role: ROLE_ADMIN }
            anonymous: true
            logout:
                path:   /logout
                target: user_security
            form_login:
                login_path: user_login
                check_path: user_login

    # Note: Only the *first* access control that matches will be used
    access_control:
         # SYSTEM (LOGIN, LOGOUT, PASSWORD_RECOVERY, ...)
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
         - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
         - { path: ^/security, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
         - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
         - { path: ^/password_forgotten, roles: IS_AUTHENTICATED_ANONYMOUSLY  }

        # ITEM VIEW CLUE CAN BE ACCESSED BY EVERYONE
         - { path: ^/item/view/(.*), roles: ROLE_USER  }

        # ITEM CREATION, (DI/A)SSOCIATION, ... CAN BE ACCESSED ONLY BY ST
         - { path: ^/item, roles: ROLE_STORY_TELLER  }

        #THIS ROUTE CAN BE ACCESSED BY EVERYONE
         - { path: ^/, roles: ROLE_USER }
